id: PFE84A2FF
initial_creation_type: input
source_metadata:
  title: Satyasiddhiśāstram
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Udip Shakya
  contribution to GRETIL: Udip Shakya
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:15:54.480561'
last_modified_at: '2022-03-09T15:15:54.480577'
